feat: project structure
350StealthDelta/java-explore-with-me pull request #4
Opened 2022-11-18 14:45 UTC by 350StealthDelta

Base project structure

2022-12-04 13:09 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-12-04 13:09 UTC, FanaticFiz commented on explore-server/pom.xml
> +<!--                <configuration>
не оставляем закомментированного кода

2022-12-04 13:09 UTC, FanaticFiz commented on explore-server/src/main/java/yandex/practicum/stealth/explore/server/category/service/CategoryService.java
> +    List<CategoryDto> getCategories(Integer from, Integer size);
Методы не висят в воздухе!
Поэтому нет нужды в них повторять название сущности, например: `categoryService.getCategories()`

Получается масло-масляное! 

Лучше: `categoryService.getAll()` `categoryService.create()`

2022-12-04 13:09 UTC, FanaticFiz commented on explore-server/src/main/java/yandex/practicum/stealth/explore/server/category/service/CategoryServiceImpl.java
> +        return categoryRepository.findById(catId).orElseThrow(() -> {
Методы в цепочках лучше располагать каждый на новой строке

```
        return categoryRepository.findById(catId)
                                 .orElseThrow(() -> {
                                     throw new CustomEntityNotFoundException(
                                             String.format("Category with id=%s was not found.", catId));
                                 });
```

2022-12-04 13:09 UTC, FanaticFiz commented on explore-server/src/main/java/yandex/practicum/stealth/explore/server/category/service/CategoryServiceImpl.java
> +                .skip(from)
Это не годится!
Мы не можем позволить себе достать всё а потом применять лимиты.

Смысл именно в том чтобы облегчить запрос и итоговое кол-во сущностей при выборке из БД.

Вообще эти from и size должны превратиться в Pageable обьект и должны быть переданы в сервис, JPA как раз умеет с ним работать, вот сигнатура метода

`Page<T> findAll(Pageable pageable);`

2022-12-04 13:09 UTC, FanaticFiz commented on explore-server/src/main/java/yandex/practicum/stealth/explore/server/category/service/CategoryServiceImpl.java
> +        return catToDto(categoryRepository.save(category));
Не прячем главное действие... Главное тут это сохранение, оно достойно отдельной строки кода.

```
    @Override
    @Transactional
    public CategoryDto addCategory(NewCategoryDto body) {
        Category saved = categoryRepository.save(newDtoToCat(body));
        
        return catToDto(saved);
    }
```

2022-12-04 13:09 UTC, FanaticFiz commented on explore-server/src/main/java/yandex/practicum/stealth/explore/server/compilation/model/Compilation.java
> +    @Column(name = "compilations_title")
Зачем это дополнение к нормальному названию `title`, да и так понятно чей это title!

Почему тогда соседние поле не называются одинаково с этим?
`compilations_pinned`, `compilations_events` ?

Плохо когда что то не консистентно!

2022-12-04 13:09 UTC, FanaticFiz commented on explore-server/src/main/java/yandex/practicum/stealth/explore/server/compilation/service/CompilationServiceImpl.java
> +    private static void eventsInCompExistCheck(Long compId, Long eventId, Compilation compilation) {
Если мы собираемся кидать ексепшн при проверке, то лучше дать методу название по типу: `throwПоКакойтоПричине`

2022-12-04 13:09 UTC, FanaticFiz commented on explore-server/src/main/java/yandex/practicum/stealth/explore/server/event/dto/EventFullDto.java
> +    private String annotation;
Многие поля пересекаются в этих двух dto: EventFullDto/EventShortDto
Чтобы не дублировать их, что можно сделать?

2022-12-04 13:09 UTC, FanaticFiz commented on explore-server/src/main/java/yandex/practicum/stealth/explore/server/event/model/Event.java
> +    @Column(name = "events_id")
Делай отступы между полями... когда много аннотаций всё сливается.

2022-12-04 13:09 UTC, FanaticFiz commented on explore-server/src/main/java/yandex/practicum/stealth/explore/server/event/service/EventServiceImpl.java
> +        event.addView();
А почему не пользуемся `statsClient` и его и не видно нигде... 
Статистика же лежит в другом сервисе, почему мы делаем просто +1 !?

2022-12-04 13:09 UTC, FanaticFiz commented on explore-server/src/main/java/yandex/practicum/stealth/explore/server/exception/CustomEntityNotFoundException.java
> +public class CustomEntityNotFoundException extends RuntimeException {
Просто: `NotFoundException`

2022-12-04 13:09 UTC, FanaticFiz commented on explore-server/src/main/java/yandex/practicum/stealth/explore/server/exception/RequestWithEnErrorException.java
> +public class RequestWithEnErrorException extends RuntimeException {
Просто BadRequestException - называем общие ексепшены согласно тем кодам которые будут отданы клиенту, так проще!

2022-12-04 13:09 UTC, FanaticFiz commented on explore-server/src/main/java/yandex/practicum/stealth/explore/server/request/RequestServiceImpl.java
> +        System.out.println(requests);
А это что такое? )))
А как же логгер!

2022-12-04 13:09 UTC, FanaticFiz commented on explore-server/src/main/java/yandex/practicum/stealth/explore/server/util/CustomPageRequest.java
> +public class CustomPageRequest extends PageRequest {
Не используется... да и не должен, я уже писал что существует Pageable интерфейс, родной так сказать )

2022-12-04 13:09 UTC, FanaticFiz commented on explore-server/src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=none
Я буду топить за то чтобы вы сразу привыкали к написанию файла свойств для приложения в формате `yaml -> application.yml`

Соответственно - попрошу тебя этому следовать.

Но это не обязательно требование.

2022-12-04 13:09 UTC, FanaticFiz commented on explore-stat/src/main/java/yandex/practicum/stealth/explore/stat/StatApplication.java
> +    public static void main(String[] args) {
Обожаю этот класс, в нём никто не делает ошибок!! )))

2022-12-04 13:09 UTC, FanaticFiz commented on explore-stat/src/main/java/yandex/practicum/stealth/explore/stat/dao/StatRepository.java
> +    @Query("select new yandex.practicum.stealth.explore.stat.model.ViewEntity(s.app, s.uri, count(s.ip)) from StatEntity s " +
Выделяй SQL команды, записывая их в верхнем регистре: `SELECT/ADD/FROM`

2022-12-04 17:37 UTC, 350StealthDelta commented on explore-server/src/main/java/yandex/practicum/stealth/explore/server/category/service/CategoryService.java
> +    List<CategoryDto> getCategories(Integer from, Integer size);
Принято.

2022-12-04 17:38 UTC, 350StealthDelta commented on explore-server/src/main/java/yandex/practicum/stealth/explore/server/category/service/CategoryServiceImpl.java
> +        return categoryRepository.findById(catId).orElseThrow(() -> {
Спасибо, учту.

2022-12-04 17:55 UTC, 350StealthDelta commented on explore-server/src/main/java/yandex/practicum/stealth/explore/server/category/service/CategoryServiceImpl.java
> +                .skip(from)
Забыл переделать :)
Даже класс с кастомным PageRequest в утилитах сделал, для того, чтобы из этих from и size делать нормальный PageRequest, но поменять все на нормальную реализацию забыл.

2022-12-04 17:57 UTC, 350StealthDelta commented on explore-server/src/main/java/yandex/practicum/stealth/explore/server/category/service/CategoryServiceImpl.java
> +        return catToDto(categoryRepository.save(category));
Спасибо, поправил.

2022-12-04 18:01 UTC, 350StealthDelta commented on explore-server/src/main/java/yandex/practicum/stealth/explore/server/request/RequestServiceImpl.java
> +        System.out.println(requests);
А это хвосты от лютого дебага ))) Забыл поубирать.
Кстати, такой вывод легче, как оказалось, найти среди тонны логов в консоли - он выделяется отсутствием оформления и сразу бросается в глаза.

2022-12-04 18:04 UTC, 350StealthDelta commented on explore-server/src/main/java/yandex/practicum/stealth/explore/server/util/CustomPageRequest.java
> +public class CustomPageRequest extends PageRequest {
У нас в запросах, на сколько я понял, передается не номер страницы во from, а количество позиций, которые надо пропустить. А родной PageRequest принимает именно номер страницы. Чтобы не пересчитывать каждый раз, когда надо создавать новый PageRequest, решил сделать отдельную реализацию, которая сама все будет делать как надо, но в итоге возвращает все тот же PageRequest.

2022-12-04 18:05 UTC, 350StealthDelta commented on explore-server/src/main/java/yandex/practicum/stealth/explore/server/util/CustomPageRequest.java
> +public class CustomPageRequest extends PageRequest {
В итоге сейчас реализовал через этот класс создание PageRequest для соответсвующих запросов.

2022-12-04 18:10 UTC, 350StealthDelta commented on explore-server/src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=none
Сейчас на работе все на Gradle и в yaml. Пытаюсь осваиваться, но пока еще не привычно ) Но в целом да, получается удобнее и читабельнее.

2022-12-04 18:11 UTC, 350StealthDelta commented on explore-stat/src/main/java/yandex/practicum/stealth/explore/stat/dao/StatRepository.java
> +    @Query("select new yandex.practicum.stealth.explore.stat.model.ViewEntity(s.app, s.uri, count(s.ip)) from StatEntity s " +
Исправил.

2022-12-04 18:36 UTC, 350StealthDelta commented on explore-server/src/main/java/yandex/practicum/stealth/explore/server/compilation/model/Compilation.java
> +    @Column(name = "compilations_title")
Спасибо, что напомнил! 
Поправил названия полей в таблицах, убрал длинные и добавил префиксы с отсылками к конкретным таблицам. Когда пишешь какие-нибудь джоины, то с префиксами легче понять, какой id от какой таблицы у тебя джойнится.

2022-12-04 18:42 UTC, 350StealthDelta commented on explore-server/src/main/java/yandex/practicum/stealth/explore/server/compilation/service/CompilationServiceImpl.java
> +    private static void eventsInCompExistCheck(Long compId, Long eventId, Compilation compilation) {
My english is not so good, as i expected ))) Поправил описание в месседже исключения и имя метода ))

2022-12-04 19:04 UTC, 350StealthDelta commented on explore-server/src/main/java/yandex/practicum/stealth/explore/server/event/dto/EventFullDto.java
> +    private String annotation;
Вынес все дублирование в абстрактный класс и переделал маппер.

2022-12-04 19:05 UTC, 350StealthDelta commented on explore-server/src/main/java/yandex/practicum/stealth/explore/server/event/model/Event.java
> +    @Column(name = "events_id")
Понял. В идее это выглядит читабельнее ))

2022-12-04 19:18 UTC, 350StealthDelta commented on explore-server/src/main/java/yandex/practicum/stealth/explore/server/exception/CustomEntityNotFoundException.java
> +public class CustomEntityNotFoundException extends RuntimeException {
Такой эксепшен уже где-то есть в библиотеках и чтобы его не перекрывать, сделал свой, кастомный.

2022-12-04 19:24 UTC, 350StealthDelta commented on explore-server/src/main/java/yandex/practicum/stealth/explore/server/exception/RequestWithEnErrorException.java
> +public class RequestWithEnErrorException extends RuntimeException {
Принял.

2022-12-05 19:12 UTC, FanaticFiz approved these changes

2022-12-05 19:12 UTC, FanaticFiz commented on explore-server/src/main/java/yandex/practicum/stealth/explore/server/category/service/CategoryService.java
> +    Category findById(Long catId);
```
CategoryDto getById(Long catId);
Category findById(Long catId);
```

Метод то один должен быть, а дальше маппер в помощь...

2022-12-05 19:12 UTC, FanaticFiz commented on explore-server/src/main/java/yandex/practicum/stealth/explore/server/compilation/AdminCompilationsController.java
> +        return ResponseEntity.status(HttpStatus.OK).build();
Есть хорошая практика делать отступ перед `return`.

Это выделяет точку выхода из метода визуально.
Есть только одно исключение: если метод начался сразу с return то отступ делать не нужно.

2022-12-05 19:12 UTC, FanaticFiz commented on explore-server/src/main/java/yandex/practicum/stealth/explore/server/event/dto/EventShortDto.java
> +//@AllArgsConstructor
мусор подчищаем...

2022-12-05 19:12 UTC, FanaticFiz commented on explore-server/src/main/java/yandex/practicum/stealth/explore/server/request/RequestServiceImpl.java
> +        ParticipationRequest request = ParticipationRequest.builder()
Почему не в мапере?

2022-12-06 05:00 UTC, merged